name: darti
description: An interpreter for a tiny subset of Dart
version: 0.0.1
repository: https://github.com/sma/darti

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.9.0
  pub_semver: ^2.1.4

dev_dependencies:
  coverage: ^1.9.2
  lints: ^5.1.0
  test: ^1.24.0
